site_name: Yanan Wu Teaching geog-247
site_description: Yanan Wu Teaching geog-247
site_author: Yanan Wu
site_url: https://gisynw.github.io/geog-247/
copyright: "Copyright &copy; 2024 - 2025 Yanan Wu"

# Repository
repo_name: gisynw/geog-247
repo_url: https://github.com/gisynw/geog-247.git

# Configuration
theme:
  language: en
  palette:
    - scheme: default
      primary: gray
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    # - toc.integrate
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.share
  # custom_dir: "docs/overrides"
  font:
    text: Google Sans
    code: Regular

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gisynw/geog-247.git
    # - icon: fontawesome/brands/google-scholar
    # link: https://scholar.google.com/citations?user=wdkZhlwAAAAJ
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/giswu
    # - icon: fontawesome/brands/instagram
    #   link: https://www.instagram.com/c17hawke/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - open-in-new-tab
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - mkdocs-pdf
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      allow_errors: false
      ignore: ["conf.py"]
      #   execute: True

nav:
    - Home: index.md
    - Syllabus:
      - Syllabus Spring 2025: "Content/Spring2025_syllabus.ipynb"
    - Softwares:
      - RStudio & R: "software/Software_Install.ipynb"
      - TexMix package in R: "software/TexMix.pdf"
    - Lectures:
      - Week 1 Introduction: "Lectures/Week01/week01_Intro.ipynb"  
      - Week 2 Inferential Statistics: "Lectures/Week02/Week02_InferentialStas.pdf"
      - Week 3 Data Exploration: "Lectures/Week03/Week03_DataExploration.pdf"
    - Labs:
      - Practice 01: "Labs/Practice01/Practice01.ipynb"
      - Lab 01: "Labs/Lab01/Lab01geog247_347Spring2025.pdf"
    - Code:
      - Week 1 Code: "Demo/Week01_code.ipynb"
      - Week 2 Code: "Demo/Week02_code.ipynb"
      - Week 3 Code: "Demo/Week03_code.ipynb"