---
title: "Week_lecture"
output: html_document
date: "2025-01-20"
---
```{r}
data('advertising')
```

```{r}
bivariate_model = lm(sales~TV, data = advertising)

plot(bivariate_model)

summary(bivariate_model)
```

```{r}
plot(advertising$TV, advertising$sales, 
     main = "Regression of Sales on TV Advertising",
     xlab = "TV Advertising Budget", 
     ylab = "Sales",
     pch = 16, col = "blue")

# Add regression line
abline(bivariate_model, col = "red", lwd = 2)
```
## Bivariate model based on UN Dataset
```{r}
library(carData);library(car)

data('UN')

un_model = lm(infantMortality~ppgdp, data = UN)

plot(un_model)
```


```{r}
scatterplot(infantMortality~ppgdp, data = UN,xlab = 'Gross Domestic Product per Capita', 
            ylab = 'Infant Mortality Rate (per 1000 births)')
```

```{r}
hist(CPS1988$education, breaks = 50)
```

```{r}
#############################################################
## Bivariate model based on UN Dataset                      #
#############################################################
library(carData);library(car);library(e1071);library(stats)

data('Boston')

biva_model = lm(medv~dis, data = Boston)

summary(powerTransform(Boston$dis~1))

scatterplot(medv~dis, data = Boston,xlab = 'Distance to Employment Center', 
            ylab = 'Median Value of Homes in $1000', 
            regLine = list(col = 'darkgreen'), 
            smooth = list(col.smooth = "red"))

hist(Boston$dis, breaks = 20, main = 'Distribution of Distance',
     xlab = 'Distance', probability = TRUE)
lines(density(Boston$dis), col = "blue", lwd = 2)

skewness(Boston$dis)
shapiro.test(Boston$dis)
```


